export const productsData = [
  {
    id: 'compute',
    label: 'Compute',
    category: 'Compute & Servers',
    title: 'High-Performance Compute',
    icon: 'ri-cpu-line',
    image: 'https://images.unsplash.com/photo-1591696205602-2f950c417cb9?auto=format&fit=crop&q=80&w=800',
    desc: 'At SVM, we lay the foundation for your data processing. We supply and configure high-density rack servers, blade chassis, and enterprise mainframes from top global vendors.',
    features: ['High-density blade servers', 'Fault-tolerant processing', 'Scalable computing nodes', 'High-performance computing', 'Scalable server clusters'],
  },
  {
    id: 'data-storage',
    label: 'Data Storage',
    category: 'Data Storage',
    title: 'Secure & Accessible Storage',
    icon: 'ri-hard-drive-2-line',
    image: 'https://images.unsplash.com/photo-1597852074816-d933c7d2b988?auto=format&fit=crop&q=80&w=800',
    desc: 'Keep your data accessible and secure at all times. Our storage products range from all-flash SAN arrays to high-capacity NAS systems and tape backups. We constantly verify the integrity of your storage infrastructure to address gaps for any emerging threats.',
    features: ['Enterprise SAN/NAS', 'Automated tiered storage', 'Encrypted backups', 'All-flash SAN arrays', 'Automated backup appliances'],
  },
  {
    id: 'security',
    label: 'Security',
    category: 'Security Appliances',
    title: 'Enterprise Cyber Defense',
    icon: 'ri-shield-keyhole-line',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800',
    desc: 'While digital transformation is a necessity, security is the primary concern. We implement Zero Trust architectures, advanced perimeter firewalls, and active threat detection to protect your digital assets.',
    features: ['Zero Trust networks', 'Intrusion Prevention (IPS)', 'Endpoint security (EDR)', 'Next-Gen Firewalls (NGFW)', 'VPN Gateways'],
  },
  {
    id: 'networking',
    label: 'Networking',
    category: 'Networking Gear',
    title: 'Scalable Network Infrastructure',
    icon: 'ri-router-line',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800',
    desc: 'We design, develop, install, and manage information networks for growing businesses. We provide enterprise core switches, edge routers, and Wi-Fi 6 access points to ensure a seamless flow of data across your organization.',
    features: ['SD-WAN deployment', 'High-availability routing', 'Wireless mobility solutions', 'Core & Edge Switches', 'Wi-Fi 6 Access Points'],
  },
  {
    id: 'kvm',
    label: 'KVM',
    category: 'KVM & Control Rooms',
    title: 'KVM & Control Rooms',
    icon: 'ri-keyboard-line',
    image: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=800',
    desc: 'Security and reliability are vital for command centers. With a wide range of KVM (keyboard, video, mouse) solutions and IT peripherals, we create multi-function secure work rooms for clients.',
    features: ['Secure matrix switching', 'Remote server access', 'Ergonomic command centers', 'KVM over IP', 'Secure KVM Matrix Switches'],
  },
  {
    id: 'infrastructure',
    label: 'Infrastructure',
    category: 'Infrastructure Accessories',
    title: 'Datacenter Infrastructure',
    icon: 'ri-building-4-line',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800',
    desc: 'Innovate to Transform Your IT Infrastructure. From servers to mainframes to storage systems and software, we lay the physical foundation — the power, cooling, cabling, and racks — for the next-gen IT architecture.',
    features: ['Structured cabling', 'Power & cooling management', 'Datacenter migration', 'Server Racks & Cabinets', 'Uninterruptible Power Supplies (UPS)'],
  },
];
